  
pipeline {
    environment {
    registry = "umir/java-with-maven"
    registryCredential = 'c8f7d755-bbae-455e-8f5e-2edb7a16d03f'
    dockerImage = ''
  }
    agent any
    stages {
        stage('Building image') {
            steps{
              script {
                dockerImage = docker.build registry + ":$BUILD_NUMBER"
              }
            }
        }
        stage('Deploy Image') {
          steps{
            script {
              docker.withRegistry( '', registryCredential ) {
                dockerImage.push()
              }
            }
          }
        }
        stage('Remove Unused docker image') {
          steps{
            sh "docker rmi $registry:$BUILD_NUMBER"
          }
        }
    }
}
